apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: trail-run-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: "https://github.com/VitorRemesso2050519/projeto-sd-grupo-1"
    targetRevision: joao
    path: trail-run
  destination:
    server: https://kubernetes.default.svc
    namespace: trail-run
  syncPolicy:
    automated:
      prune: true
      selfHeal: true